version: '3.8'
services:
  codify-client:
    image: maxhook/codify-client:latest
    container_name: codify-client
    restart: unless-stopped
    networks:
      - proxy-network

  codify-server:
    image: maxhook/codify-server:latest
    container_name: codify-server
    restart: unless-stopped
    environment:
      - PORT=4000
      - REDIS_URL=redis://redis:6379
    networks:
      - proxy-network
      - codify-internal

  redis:
    image: redis:alpine
    container_name: codify-redis
    restart: unless-stopped
    networks:
      - codify-internal

networks:
  proxy-network:
    external: true
  codify-internal: